on:
  push:
    branches: [ main, sophus2 ]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false


    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: build docs
        run: |
          sudo apt-get -qq update
          sudo apt-get install doxygen liblua5.3-dev ragel graphviz
          pip3 install sphinx sympy sphinx_book_theme
          cd docs
          ./make_docs.sh
          cd html-dir
          touch .nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html-dir
          publish_branch: docs
          destination_dir: latest
