name: format

on:
  push:
    branches: [ master, 23.04-beta ]
  pull_request:

  workflow_dispatch:

jobs:
  pre-commit-check:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout workspace
          uses: actions/checkout@v3
        - name: Install pre-commit and install
          run: |
            pip install pre-commit pylint sympy==1.8
            pre-commit install
        - name: Run pre-commit checks
          run: pre-commit run --all-files
